### ISSUE TITLE
Velocity Vectors

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#60]
Add or increase the scale.

**Comment by FLO-2DKaren** [comment]
Mapper had a 1x or 2x scale factor that was pretty useful.
I also think we could scale the width a little better.
Final velocity vectors are very useful because they tell you if the flow is no longer moving.  Having that option is great even if it's not scaled because if they are all small, you know you ran it long enough.

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/72:

![image](https://github.com/user-attachments/assets/7d4d6012-c398-43d7-a2f1-bf9ef160ce22)
